### ISSUE TITLE
Error when start the application

### ISSUE THREAD

**Issue by guangyi1609** [husam88/DroidbotX#3]
Hi there i had follow your steps to install all the related package. But i still getting package not found issue. Below is my error message

Traceback (most recent call last):
  File "C:\Users\new\DroidbotX-master\DroidbotX-master\droidbot\start_q_learning.py", line 17, in <module>
    from stable_baselines.common.vec_env import DummyVecEnv
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\stable_baselines\__init__.py", line 4, in <module>
    from stable_baselines.a2c import A2C
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\stable_baselines\a2c\__init__.py", line 1, in <module>
    from stable_baselines.a2c.a2c import A2C
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\stable_baselines\a2c\a2c.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

May I know what i still missing ? maybe can you provide the actual package version to use?

**Comment by ThePearhead** [comment]
Hi,
i encountered the same problem., I use tensorflow 2.7.0 and python 3.9.12.
I followed all the other instructions. 
Is DroidbotX not working with newer versions of tensorflow?
(edit: same error with tensorflow 2.8.0)
